### ISSUE TITLE
Does not seem to work since the 1.0.3 update

### ISSUE THREAD

**Issue by spiritualgeek** [doitian/obsidian-min-width#3]
I think your 1.0.3 update broke something. It has been working perfectly since until the last update

**Comment by doitian** [comment]
Is there any error in the developer console?

Open console: `Command+Option+i` on macOS and `F12 or Control+Shift+i` on Windows/Linux.

**Comment by doitian** [comment]
BTW, which Obisidian version are you using? What's your platform (macOS/Windows/Linux/iOS/Android)?

**Comment by spiritualgeek** [comment]
Apologies for the terseness of what I posted

below is a snapshot of what I'm running

Looking at the console, I don't see any errors

It's a mystery as to why the previous version was working fine :\

```
SYSTEM INFO:
	Obsidian version: v0.16.5
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 21.6.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Shimmering Focus
	Snippets enabled: 42
	Restricted mode: off
	Plugins installed: 54
	Plugins enabled: 47
```

**Comment by doitian** [comment]
Fixed for insider versions.

**Comment by spiritualgeek** [comment]
Awesome, it's working again. Thanks
